In [21]:
import pandas as pd
import numpy as np

In [22]:
# Step 1: Create sample dataset with 20 rows including missing values, duplicates, and outliers

In [23]:
data = {
    'name': ['Aarav', 'Bhavya', 'Chirag', 'Deepa', 'Ekta', 'Farhan', 'Gaurav', 'Harshita', 'Ishaan', 'Jaya',
             'Kiran', 'Lalit', 'Manisha', 'Naveen', 'Ojas', 'Pooja', 'Anand', 'Ritika', 'Bhavya', 'Tanya'],
    'age': [25, 30, 35, np.nan, 45, 40, 35, 28, 30, 32,
            25, 30, 120, 40, 29, np.nan, 33, 310, 30, 28],  # includes missing values and an outlier (120)
    'salary': [50000, 60000, 55000, 70000, np.nan, 62000, 58000, 59000, np.nan, 61000,
               50000, 60000, 1000000, 62000, 59000, 60000, 610000, 59000, 60000, 58000],  # includes missing and outlier (1,000,000)
    'department': ['HR', 'IT', 'Finance', 'HR', 'IT', 'Finance', 'HR', 'IT', 'Finance', 'HR',
                   'HR', 'IT', 'Finance', 'HR', 'IT', 'Finance', 'HR', 'IT', 'IT', 'HR']
}

In [24]:
df = pd.DataFrame(data)

In [25]:
print("Original DataFrame:")
df

Original DataFrame:

        name    age     salary department
0      Aarav   25.0    50000.0         HR
1     Bhavya   30.0    60000.0         IT
2     Chirag   35.0    55000.0    Finance
3      Deepa    NaN    70000.0         HR
4       Ekta   45.0        NaN         IT
5     Farhan   40.0    62000.0    Finance
6     Gaurav   35.0    58000.0         HR
7   Harshita   28.0    59000.0         IT
8     Ishaan   30.0        NaN    Finance
9       Jaya   32.0    61000.0         HR
10     Kiran   25.0    50000.0         HR
11     Lalit   30.0    60000.0         IT
12   Manisha  120.0  1000000.0    Finance
13    Naveen   40.0    62000.0         HR
14      Ojas   29.0    59000.0         IT
15     Pooja    NaN    60000.0    Finance
16     Anand   33.0   610000.0         HR
17    Ritika  310.0    59000.0         IT
18    Bhavya   30.0    60000.0         IT
19     Tanya   28.0    58000.0         HR

In [26]:
# Step 2: Handle missing values
# Fill missing 'age' with median, 'salary' with median

In [27]:
df['age'] = df['age'].fillna(df['age'].median())
df['salary'] = df['salary'].fillna(df['salary'].median())

In [28]:
print("After Handling missing values:")
df

After Handling missing values:

        name    age     salary department
0      Aarav   25.0    50000.0         HR
1     Bhavya   30.0    60000.0         IT
2     Chirag   35.0    55000.0    Finance
3      Deepa   31.0    70000.0         HR
4       Ekta   45.0    60000.0         IT
5     Farhan   40.0    62000.0    Finance
6     Gaurav   35.0    58000.0         HR
7   Harshita   28.0    59000.0         IT
8     Ishaan   30.0    60000.0    Finance
9       Jaya   32.0    61000.0         HR
10     Kiran   25.0    50000.0         HR
11     Lalit   30.0    60000.0         IT
12   Manisha  120.0  1000000.0    Finance
13    Naveen   40.0    62000.0         HR
14      Ojas   29.0    59000.0         IT
15     Pooja   31.0    60000.0    Finance
16     Anand   33.0   610000.0         HR
17    Ritika  310.0    59000.0         IT
18    Bhavya   30.0    60000.0         IT
19     Tanya   28.0    58000.0         HR

In [29]:
# Step 3: Remove duplicates

In [30]:
duplicates = df[df.duplicated(keep=False)]
print("Duplicate rows in the dataset:")
duplicates

Duplicate rows in the dataset:

      name   age   salary department
1   Bhavya  30.0  60000.0         IT
18  Bhavya  30.0  60000.0         IT

In [31]:
df = df.drop_duplicates()

In [32]:
print("After Removing duplicates:")
df

After Removing duplicates:

        name    age     salary department
0      Aarav   25.0    50000.0         HR
1     Bhavya   30.0    60000.0         IT
2     Chirag   35.0    55000.0    Finance
3      Deepa   31.0    70000.0         HR
4       Ekta   45.0    60000.0         IT
5     Farhan   40.0    62000.0    Finance
6     Gaurav   35.0    58000.0         HR
7   Harshita   28.0    59000.0         IT
8     Ishaan   30.0    60000.0    Finance
9       Jaya   32.0    61000.0         HR
10     Kiran   25.0    50000.0         HR
11     Lalit   30.0    60000.0         IT
12   Manisha  120.0  1000000.0    Finance
13    Naveen   40.0    62000.0         HR
14      Ojas   29.0    59000.0         IT
15     Pooja   31.0    60000.0    Finance
16     Anand   33.0   610000.0         HR
17    Ritika  310.0    59000.0         IT
19     Tanya   28.0    58000.0         HR

In [33]:
# Step 4: Type casting

In [34]:
# Use .loc to explicitly assign values to the DataFrame that is a view or slice rather than a copy

In [35]:
# df['age'] = df['age'].astype(int)
# df['salary'] = df['salary'].astype(int)
df.loc[:, 'age'] = df['age'].astype(int)
df.loc[:, 'salary'] = df['salary'].astype(int)

In [36]:
print("After Type casting:")
df

After Type casting:

        name    age     salary department
0      Aarav   25.0    50000.0         HR
1     Bhavya   30.0    60000.0         IT
2     Chirag   35.0    55000.0    Finance
3      Deepa   31.0    70000.0         HR
4       Ekta   45.0    60000.0         IT
5     Farhan   40.0    62000.0    Finance
6     Gaurav   35.0    58000.0         HR
7   Harshita   28.0    59000.0         IT
8     Ishaan   30.0    60000.0    Finance
9       Jaya   32.0    61000.0         HR
10     Kiran   25.0    50000.0         HR
11     Lalit   30.0    60000.0         IT
12   Manisha  120.0  1000000.0    Finance
13    Naveen   40.0    62000.0         HR
14      Ojas   29.0    59000.0         IT
15     Pooja   31.0    60000.0    Finance
16     Anand   33.0   610000.0         HR
17    Ritika  310.0    59000.0         IT
19     Tanya   28.0    58000.0         HR

In [37]:
# Step 5: Handle outliers using IQR for 'age' and 'salary'

In [38]:
def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

In [39]:
# Apply IQR Method
df = remove_outliers(df, 'age')
df = remove_outliers(df, 'salary')

In [43]:
print(remove_outliers(df, 'age'))
print(remove_outliers(df, 'salary'))

        name   age   salary department
1     Bhavya  30.0  60000.0         IT
2     Chirag  35.0  55000.0    Finance
5     Farhan  40.0  62000.0    Finance
6     Gaurav  35.0  58000.0         HR
7   Harshita  28.0  59000.0         IT
8     Ishaan  30.0  60000.0    Finance
9       Jaya  32.0  61000.0         HR
11     Lalit  30.0  60000.0         IT
13    Naveen  40.0  62000.0         HR
14      Ojas  29.0  59000.0         IT
15     Pooja  31.0  60000.0    Finance
19     Tanya  28.0  58000.0         HR
        name   age   salary department
1     Bhavya  30.0  60000.0         IT
4       Ekta  45.0  60000.0         IT
6     Gaurav  35.0  58000.0         HR
7   Harshita  28.0  59000.0         IT
8     Ishaan  30.0  60000.0    Finance
9       Jaya  32.0  61000.0         HR
11     Lalit  30.0  60000.0         IT
14      Ojas  29.0  59000.0         IT
15     Pooja  31.0  60000.0    Finance
19     Tanya  28.0  58000.0         HR

In [40]:
print("After Handling outliers:")
df.reset_index(drop=True)

After Handling outliers:

        name   age   salary department
0     Bhavya  30.0  60000.0         IT
1     Chirag  35.0  55000.0    Finance
2       Ekta  45.0  60000.0         IT
3     Farhan  40.0  62000.0    Finance
4     Gaurav  35.0  58000.0         HR
5   Harshita  28.0  59000.0         IT
6     Ishaan  30.0  60000.0    Finance
7       Jaya  32.0  61000.0         HR
8      Lalit  30.0  60000.0         IT
9     Naveen  40.0  62000.0         HR
10      Ojas  29.0  59000.0         IT
11     Pooja  31.0  60000.0    Finance
12     Tanya  28.0  58000.0         HR

In [44]:
df.info

<bound method DataFrame.info of         name   age   salary department
1     Bhavya  30.0  60000.0         IT
2     Chirag  35.0  55000.0    Finance
4       Ekta  45.0  60000.0         IT
5     Farhan  40.0  62000.0    Finance
6     Gaurav  35.0  58000.0         HR
7   Harshita  28.0  59000.0         IT
8     Ishaan  30.0  60000.0    Finance
9       Jaya  32.0  61000.0         HR
11     Lalit  30.0  60000.0         IT
13    Naveen  40.0  62000.0         HR
14      Ojas  29.0  59000.0         IT
15     Pooja  31.0  60000.0    Finance
19     Tanya  28.0  58000.0         HR>

In [45]:
# Visulization